server.port=8081

spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5433/cabsy_user
spring.datasource.username=cabsy
spring.datasource.password=cabsy
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

cabsy.jwt.secret=${CABSY_JWT_SECRET}
cabsy.jwt.expiration-ms=86400000
